# Generated by Django 3.2.8 on 2021-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(related_name='store', to='book.Book'),
        ),
    ]
